backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "bio"
    label: "Bio"
    folder: "content/bio"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "DD-MM-YYYY" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Reading Time", name: "time", widget: "string" }
      - {
        label: "Featured Image",
        name: "featuredImage",
        widget: "image",
        media_library: {
          config: {
            multiple: false
          }
        },
        tagname: ''
      }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "technologies"
    label: "Technologies"
    folder: "content/technologies"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Stack", name: "stack", widget: "select", options: ["LANGUAGE", "FRONTEND", "BACKEND", "DEVOPS", "INFRA", "LIBRARY"]}
      - { label: "Website", name: "website", widget: "string" }
      - {
        label: "Featured Image",
        name: "featuredImage",
        widget: "image",
        media_library: {
          config: {
            multiple: false
          }
        },
        tagname: ''
      }
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Year", name: "year", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Project URL", name: "projectUrl", widget: "string" }
      - { label: "Repository URL", name: "repositoryUrl", widget: "string" }
      - { label: "Type", name: "type", widget: "select", options: ["front-end", "back-end", "full-stack", "dev-ops", "infra"]}
      - { label: "Body", name: "body", widget: "markdown" }
      - {
        label: "Featured Image",
        name: "featuredImage",
        widget: "image",
        media_library: {
          config: {
            multiple: false
          }
        },
        tagname: ''
      }
  - name: "opensource"
    label: "Opensource"
    folder: "content/opensource"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", , format: "YYYY" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Project URL", name: "projectUrl", widget: "string" }
      - { label: "Repository URL", name: "repositoryUrl", widget: "string" }
      - {
        label: "Featured Image",
        name: "featuredImage",
        widget: "image",
        media_library: {
          config: {
            multiple: false
          }
        },
        tagname: ''
      }
  - name: "experience"
    label: "Experience"
    folder: "content/experience"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Role", name: "role", widget: "string" }
      - {
        label: "Start Month",
        name: "startMonth",
        widget: "select",
        options:
          [
            "Jan",
            "Feb",
            "Mar",
            "Apr",
            "May",
            "Jun",
            "Jul",
            "Aug",
            "Sep",
            "Oct",
            "Nov",
            "Dec"
          ]
      }
      - { label: "Start Year", name: "startYear", widget: "string" }
      - {
        label: "End Month",
        name: "endMonth",
        widget: "select",
        options:
          [
            "Jan",
            "Feb",
            "Mar",
            "Apr",
            "May",
            "Jun",
            "Jul",
            "Aug",
            "Sep",
            "Oct",
            "Nov",
            "Dec"
          ]
      }
      - { label: "End Year", name: "endYear", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Website", name: "website", widget: "string" }
      - {
        label: "Company Logo",
        name: "companyLogo",
        widget: "image",
        media_library: {
          config: {
            multiple: false
          }
        },
        tagname: ''
      }
